# Generated by Django 4.2.7 on 2023-12-29 19:50

import accounts_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts_app.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verify",
            field=models.BooleanField(default=False, verbose_name="Почта подтверждена"),
        ),
    ]
