# Generated by Django 4.2.7 on 2023-11-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="имя отделения"),
                ),
                ("phones", models.CharField(max_length=255, verbose_name="телефоны")),
                ("address", models.CharField(max_length=255, verbose_name="адрес")),
                (
                    "order",
                    models.IntegerField(
                        verbose_name="порядок отображения",
                        default=0,
                    )
                ),
            ],
            options={
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
                "ordering": ("order",),
            },
        ),
    ]
