# Generated by Django 4.2.7 on 2023-11-28 12:47

from django.db import migrations, models
import store_app.utils.HashStorage


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0002_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=store_app.utils.HashStorage.HashStorage(),
                upload_to=store_app.utils.HashStorage.product_preview_images,
                verbose_name="изображение",
            ),
        ),
    ]
