# Generated by Django 4.2.7 on 2024-01-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0005_product_seller"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name", "price", "create_date", "modify_date", "category"),
                "permissions": [
                    ("can_unpublished_product", "Может отменять публикацию продукта")
                ],
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="опубликовано"),
        ),
    ]
