# Generated by Django 4.2.7 on 2024-01-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0006_alter_product_options_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name", "price", "create_date", "modify_date", "category"),
                "permissions": [
                    ("can_unpublished_product", "Может отменять публикацию продукта"),
                    ("can_change_product_name", "Может изменять название продукта"),
                    (
                        "can_change_product_description",
                        "Может изменять описание продукта",
                    ),
                    (
                        "can_change_product_category",
                        "Может изменять категорию продукта",
                    ),
                ],
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
